# Generated by Django 4.1.7 on 2023-03-18 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='professors',
            name='apellido',
            field=models.CharField(default='0000', editable=False, max_length=30),
        ),
        migrations.AddField(
            model_name='professors',
            name='correo',
            field=models.EmailField(default='0000', editable=False, max_length=254),
        ),
        migrations.AddField(
            model_name='professors',
            name='nombre',
            field=models.CharField(default='0000', editable=False, max_length=30),
        ),
    ]
