# Generated by Django 4.1.7 on 2023-03-18 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_students_apellido_students_correo_students_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregables',
            name='nombre',
            field=models.CharField(default='0000', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='entregables',
            name='num',
            field=models.IntegerField(default='0000', editable=False),
        ),
    ]
