# Generated by Django 4.1.7 on 2023-03-18 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0005_entregables_nombre_entregables_num'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Entregables',
            new_name='Entregable',
        ),
        migrations.RenameModel(
            old_name='Professors',
            new_name='Professor',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
        migrations.DeleteModel(
            name='Cursos',
        ),
    ]
